import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
// import Script from "next/script";

import "./globals.css"
import MenuLateral from "./components/MenuLateral";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        

        <div className="container-fluid">
          <div className="row">
            <div className="col-2 menuLateral">
              <MenuLateral/>
            </div>
            <div className="col-10">
              {children}
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
