import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Script from "next/script";

import "./globals.css"
import MenuLateral from "./components/MenuLateral";
import TopBar from "./components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (!theme) {
                    theme = 'light';
                  }
                  if (theme === 'dark') {
                    document.documentElement.setAttribute('data-theme', 'dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} app-bg`}>
        
        <div className="layout-wrapper d-flex w-100 vh-100 overflow-hidden">
          
          <MenuLateral />

          {/* Área de Conteúdo */}
          <div className="main-content-wrapper flex-grow-1 d-flex flex-column h-100 overflow-hidden" style={{ minWidth: 0 }}>
            <TopBar />
            
            <main className="flex-grow-1 p-3 p-md-4 w-100" style={{ overflowX: "hidden", overflowY: "auto" }}>
              {children}
            </main>
          </div>

        </div>

        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous" />
      </body>
    </html>
  );
}
